name: Implement gh-deploy with GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-changelog-plugin
      - run: pip install neoteroi-mkdocs
      - run: pip install mkdocs-statistics-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-print-site-plugin
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip3 install mdx_truly_sane_lists
      - run: git clone https://github.com/TonyCrane/mkdocs-toolchain.git
      - run: cd mkdocs-toolchain/mkdocs-toc-plugin
      - run: ls      
      - run: pip install .
      - run: mkdocs gh-deploy --force