name: Implement gh-deploy with GitHub Actions
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4

    #   - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
    #   - uses: actions/cache@v4
    #     with:
    #       key: mkdocs-material-${{ env.cache_id }}
    #       path: .cache
    #       restore-keys: |
    #         mkdocs-material-
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-changelog-plugins
      - run: pip install neoteroi-mkdocs
      - run: pip install mkdocs-statistics-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-print-site-plugin
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip3 install mdx_truly_sane_lists
      - run: mkdocs gh-deploy --force